
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sanzaa?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: letmein
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8InnoDBDialect
          format_sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
#    sql:
#      init:
#        mode: never

#spring:
#  datasource:
#    url: jdbc:mysql://mysqldb/sanzaa #change this to your database url
#    password:  letmein #change this to your database username
#    username: root #change this to your database password
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect