version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
#    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"



#version: '3.8'
#
#services:
#  server:
#    build: ./
##      context: .
##      dockerfile: docker-compose.yml
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysqldb
#
#  mysqldb:
#    image: mysql:5.7
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}